window.BEGINNER_GUIDE_TRANSLATIONS = {
    en: {
        allData: {
            1: [
                "1. How to Register",
                "- Enter your mobile phone number ",
                "- Set your password (minimum 8 characters, including letters and numbers) ",
                "- Confirm password",
                "- Enter invitation code",
                `- Click "I have read and agree"`,
                `- Click "Register"`,
            ],
            2: [
                "2. How to Bet in WINGO Games",
                "- Enter WINGO game",
                "- Select game duration (1, 3, 5, or 10 minutes)",
                "Betting Options:",
                "- Green: Numbers 1, 3, 7, 9",
                "- Red: Numbers 2, 4, 6, 8",
                "- Purple: Numbers 0 or 5",
                "- Small: Numbers 0, 1, 2, 3, 4",
                "- Large: Numbers 5, 6, 7, 8, 9",
                "Prohibited Betting Combinations:",
                "- Simultaneous bets on Large and Small",
                "- Simultaneous bets on Red and Green",
                "- Betting on more than 7 numbers at once",
            ],
            3: [
                "3. How to Deposit Click the wallet icon, then select deposit. ",
            ],
            4: [
                "4. How to Withdraw Click the wallet menu, then select withdraw.",
                "- Enter withdrawal amount",
                "- Ensure your total bet balance is zero",
                "- Select or add your bank account",
                "- Enter withdrawal amount ",
                "- Enter your login password",
            ],
            5: [
                '5. Betting History After placing a bet, access "My History" to view your betting records. Use trend charts to analyze patterns for future bets and view previous game results.',
            ],
            6: [
                "6. Transactions Access all account transactions and activities through the transactions section in the account menu.",
            ],
            7: [
                "7. Change Password",
                "- Log in to your YANO 777 account",
                "- Select Account",
                "- Go to Settings menu",
                "- Choose Login Password",
                "- Enter current password",
                "- Enter new password",
                "- Confirm new password",
                "- Select Save Changes",
            ],
            8: [
                "8. Add Bank Account",
                "- Log in to your YANO 777 account",
                "- Select Wallet menu",
                "- Choose Withdraw menu",
                "- Click Add Bank",
                "- Complete all required fields",
                "- Click Save",
            ],
            9: [
                "9. Forgot Password",
                "- Visit YANO 777",
                "- Select Settings",
                "- Choose Forgot Password",
                "- Enter original password",
                "- Enter new password",
                "- Confirm new password",
                "- Click Reset",
            ],
            10: [
                "10. About Access the About section to view the Privacy Policy and Risk Disclosure Agreement details.",
            ],
            11: [
                "11. Gifts",
                "- Log in to your YANO 777 account",
                "- Select Account",
                "- Choose Gift menu",
                "- Enter gift code",
            ],
        },
        urlData: ["./images/account/guide_1.png", "./images/account/guide_2.png", "./images/account/guide_3.png", "./images/account/guide_4.png", "./images/account/guide_5.png", "./images/account/guide_6.png", "./images/account/guide_7.png", "./images/account/guide_8.png", "./images/account/guide_9.png", "./images/account/guide_10.png", "./images/account/guide_11.png"]
    },
    hi: {
        allData: {
            1: [
                "1. पंजीकरण कैसे करें",
                "- अपना मोबाइल नंबर दर्ज करें ",
                "- अपना पासवर्ड सेट करें (न्यूनतम 8 अक्षर, अक्षर और संख्या सहित)",
                "- पासवर्ड की पुष्टि करें",
                "- आमंत्रण कोड दर्ज करें",
                `- "मैंने पढ़ लिया और सहमत हूं" पर क्लिक करें`,
                `- "रजिस्टर" पर क्लिक करें`,
            ],
            2: [
                "2. WINGO गेम्स में दांव कैसे लगाएं",
                "- WINGO गेम में प्रवेश करें",
                "- गेम अवधि चुनें (1, 3, 5, या 10 मिनट)",
                "दांव विकल्प:",
                "- हरा: संख्या 1, 3, 7, 9",
                "- लाल: संख्या 2, 4, 6, 8",
                "- बैंगनी: संख्या 0 या 5",
                "- छोटा: संख्या 0, 1, 2, 3, 4",
                "- बड़ा: संख्या 5, 6, 7, 8, 9",
                "निषिद्ध दांव संयोजन:",
                "- बड़ा और छोटा पर एक साथ दांव",
                "- लाल और हरा पर एक साथ दांव",
                "- एक बार में 7 से अधिक संख्याओं पर दांव",
            ],
            3: [
                "3. जमा कैसे करें वॉलेट आइकन पर क्लिक करें, फिर जमा चुनें",
            ],
            4: [
                "4. निकासी कैसे करें वॉलेट मेनू पर क्लिक करें, फिर निकासी चुनें",
                "- निकासी राशि दर्ज करें",
                "- सुनिश्चित करें कि आपका कुल दांव शेष शून्य है",
                "- अपना बैंक खाता चुनें या जोड़ें",
                "- निकासी राशि दर्ज करें ",
                "- अपना लॉगिन पासवर्ड दर्ज करें",
            ],
            5: [
                '5. दांव इतिहास दांव लगाने के बाद "मेरा इतिहास" देखें। भविष्य के दांवों के लिए ट्रेंड चार्ट्स का उपयोग करें और पिछले गेम परिणाम देखें',
            ],
            6: [
                "6. लेन-देन खाता मेनू में लेन-देन सेक्शन के माध्यम से सभी ट्रांजैक्शन देखें",
            ],
            7: [
                "7. पासवर्ड बदलें",
                "- अपने YANO 777 खाते में लॉग इन करें",
                "- खाता चुनें",
                "- सेटिंग्स मेनू पर जाएं",
                "- लॉगिन पासवर्ड चुनें",
                "- वर्तमान पासवर्ड दर्ज करें",
                "- नया पासवर्ड दर्ज करें",
                "- नए पासवर्ड की पुष्टि करें",
                "- परिवर्तन सहेजें का चयन करें",
            ],
            8: [
                "8. बैंक खाता जोड़ें",
                "- अपने YANO 777 खाते में लॉग इन करें",
                "- वॉलेट मेनू चुनें",
                "- निकासी मेनू चुनें",
                "- बैंक जोड़ें पर क्लिक करें",
                "- सभी आवश्यक फ़ील्ड भरें",
                "- सहेजें पर क्लिक करें",
            ],
            9: [
                "9. पासवर्ड भूल गए",
                "- YANO 777 पर जाएं",
                "- सेटिंग्स चुनें",
                "- पासवर्ड भूल गए चुनें",
                "- मूल पासवर्ड दर्ज करें",
                "- नया पासवर्ड दर्ज करें",
                "- नए पासवर्ड की पुष्टि करें",
                "- रीसेट पर क्लिक करें",
            ],
            10: [
                "10. के बारे में गोपनीयता नीति और जोखिम प्रकटीकरण समझौता विवरण देखने के लिए 'के बारे में' सेक्शन पर जाएं",
            ],
            11: [
                "11. उपहार",
                "- अपने YANO 777 खाते में लॉग इन करें",
                "- खाता चुनें",
                "- उपहार मेनू चुनें",
                "- गिफ्ट कोड दर्ज करें",
            ],
        },
        urlData: ["./images/account/guide_1.png", "./images/account/guide_2.png", "./images/account/guide_3.png", "./images/account/guide_4.png", "./images/account/guide_5.png", "./images/account/guide_6.png", "./images/account/guide_7.png", "./images/account/guide_8.png", "./images/account/guide_9.png", "./images/account/guide_10.png", "./images/account/guide_11.png"]
    },
    ar: {
        allData: {
            1: [
                "1. كيفية التسجيل",
                "- أدخل رقم هاتفك المحمول",
                "- عيّن كلمة المرور (بحد أدنى 8 أحرف تتضمن أرقامًا وحروفًا)",
                "- أكد كلمة المرور",
                "- أدخل رمز الدعوة",
                `- انقر على “لقد قرأت وأوافق”`,
                `- انقر على “تسجيل”`,
            ],
            2: [
                "2. كيفية المراهنة في ألعاب WINGO",
                "- ادخل إلى لعبة WINGO",
                "- اختر مدة اللعبة (1، 3، 5، أو 10 دقائق)",
                "خيارات المراهنة:",
                "- الأخضر: الأرقام 1، 3، 7، 9",
                "- الأحمر: الأرقام 2، 4، 6، 8",
                "- البنفسجي: الأرقام 0 أو 5",
                "- صغير: الأرقام 0، 1، 2، 3، 4",
                "- كبير: الأرقام 5، 6، 7، 8، 9",
                "الرهانات المحظورة:",
                "- المراهنة في الوقت نفسه على “كبير” و”صغير”",
                "- المراهنة في الوقت نفسه على “أحمر” و”أخضر”",
                "- المراهنة على أكثر من 7 أرقام في الوقت نفسه",
            ],
            3: [
                "3. كيفية الإيداع: اضغط على أيقونة المحفظة ثم اختر “إيداع”.",
            ],
            4: [
                "4. كيفية السحب: افتح قائمة المحفظة ثم اختر “سحب”.",
                "- أدخل مبلغ السحب",
                "- تأكد أن رصيد المراهنات الكلي يساوي صفرًا",
                "- اختر أو أضف حسابك البنكي",
                "- أدخل مبلغ السحب",
                "- أدخل كلمة مرور تسجيل الدخول",
            ],
            5: [
                "5. سجل المراهنات: بعد وضع الرهان، انتقل إلى “سجلي” لعرض سجلات المراهنة. استخدم الرسوم البيانية لتحليل الاتجاهات وتوقع نتائج المستقبل.",
            ],
            6: [
                "6. المعاملات: يمكنك الوصول إلى جميع معاملات الحساب والنشاطات من خلال قسم المعاملات في القائمة.",
            ],
            7: [
                "7. تغيير كلمة المرور",
                "- قم بتسجيل الدخول إلى حساب YANO 777",
                "- اختر “الحساب”",
                "- انتقل إلى قائمة الإعدادات",
                "- اختر “كلمة مرور تسجيل الدخول”",
                "- أدخل كلمة المرور الحالية",
                "- أدخل كلمة المرور الجديدة",
                "- أكد كلمة المرور الجديدة",
                "- اختر “حفظ التغييرات”",
            ],
            8: [
                "8. إضافة حساب بنكي",
                "- قم بتسجيل الدخول إلى حساب YANO 777",
                "- اختر قائمة المحفظة",
                "- اختر “السحب”",
                "- اضغط على “إضافة بنك”",
                "- أكمل جميع الحقول المطلوبة",
                "- اضغط “حفظ”",
            ],
            9: [
                "9. نسيت كلمة المرور",
                "- قم بزيارة YANO 777",
                "- اختر “الإعدادات”",
                "- اختر “نسيت كلمة المرور”",
                "- أدخل كلمة المرور الأصلية",
                "- أدخل كلمة مرور جديدة",
                "- أكد كلمة المرور الجديدة",
                "- اضغط على “إعادة تعيين”",
            ],
            10: [
                "10. حول: ادخل إلى قسم “حول” لعرض تفاصيل سياسة الخصوصية واتفاقية الإفصاح عن المخاطر.",
            ],
            11: [
                "11. الهدايا",
                "- قم بتسجيل الدخول إلى حساب YANO 777",
                "- اختر “الحساب”",
                "- اختر قائمة “الهدية”",
                "- أدخل رمز الهدية",
            ],
        },
        urlData: ["./images/account/guide_1.png", "./images/account/guide_2.png", "./images/account/guide_3.png", "./images/account/guide_4.png", "./images/account/guide_5.png", "./images/account/guide_6.png", "./images/account/guide_7.png", "./images/account/guide_8.png", "./images/account/guide_9.png", "./images/account/guide_10.png", "./images/account/guide_11.png"]
    },
}